<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink_3</name>
   <tag></tag>
   <elementGuidId>98d89cb0-590b-47e7-9bbb-8a0b813d67ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'สรุปรายการ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_7500 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbd1a8df-3357-47a7-9c8d-a4cf65ae690e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>f07fae2a-2ea6-456d-9b4a-1390c0142022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2aeb8a7b-4761-40f2-b7b7-640f23c05f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>5d49a4fd-af43-45d6-a72b-f4c8b930f5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_menu('7500');</value>
      <webElementGuid>b434097c-1544-444b-92c5-c706dbaf22cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการ</value>
      <webElementGuid>ac143577-43b5-48f1-b2c4-5b3bb3f36744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_7500&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>77570b27-a5e3-459e-8116-2b56d67df245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>f51ffce6-7236-444f-b278-e24f1575da97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;show_menu('7500');&quot;]</value>
      <webElementGuid>99023f60-34bc-4636-b1f2-33e2ef009c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_7500']/a</value>
      <webElementGuid>ab9fe187-70ba-4e51-b824-b2c0aa21d223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการ')]</value>
      <webElementGuid>4d14d9fa-0b60-4a0a-8e62-ba9fa4728aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/preceding::a[6]</value>
      <webElementGuid>5031d5b2-e286-4dcf-8594-2fb55e66f2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการ']/parent::*</value>
      <webElementGuid>72040ce8-5f40-4707-87d8-f84d9e9a7309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>604859f0-8513-453c-89ef-c3d0984dcb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>4b84337b-cca2-4c2d-b067-d3f8a0f58bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'สรุปรายการ' or . = 'สรุปรายการ')]</value>
      <webElementGuid>550fde0f-fe8d-400c-82a4-648dd027031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[3]</value>
      <webElementGuid>c11be172-911d-4978-9b66-9d5f7c869437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7130']/a</value>
      <webElementGuid>461e0b83-878a-47f3-9ef3-c64c31762467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>1b96976a-edca-43f2-9395-e358f6ba9340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>7d1839b4-6fc4-46ca-a05e-c943393060ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ค้นหารายการ/ยกเลิกรายการ'])[1]/preceding::a[1]</value>
      <webElementGuid>8e8dc03d-d58b-481c-b024-7f2c91187546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สับเปลี่ยนกองทุน']/parent::*</value>
      <webElementGuid>5ff30102-b2bf-459e-88cd-2bee0fea172a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7130.jsp')]</value>
      <webElementGuid>c7e8c0e0-7f57-42d5-b417-9d26915101d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a</value>
      <webElementGuid>091341b3-36be-4692-b710-08ff5ad28cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7130.jsp' and (text() = 'สับเปลี่ยนกองทุน' or . = 'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>a6f318f9-16c9-436c-a71f-ebf7b48158bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[2]</value>
      <webElementGuid>821e0014-fe67-488a-af4e-d96db77dcd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7120']/a</value>
      <webElementGuid>d7cde2a2-1935-4b95-8f77-3cd95442ff4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>8d44c914-3be0-4ff9-ae63-5769c75d8f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>7dcf3f82-2128-4fe4-a207-be1e1831f9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สับเปลี่ยนกองทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>b0ec4bdc-c655-463b-a900-21381e90930c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ขายคืนหน่วยลงทุน']/parent::*</value>
      <webElementGuid>f9d3ef68-5c00-4b0f-9a01-c1022e3f6150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7120.htm')]</value>
      <webElementGuid>972a666c-f2f9-45d1-8f92-52b8aa80130e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>4e38c5d0-c330-44e2-a961-850bc629bb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7120.htm' and (text() = 'ขายคืนหน่วยลงทุน' or . = 'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>596d43bf-621f-4a00-ac3d-b6c78ce3ea94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_form();']</value>
      <webElementGuid>5fbc8b10-872b-44ea-96d9-3206df716731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7110']/a</value>
      <webElementGuid>8d68a401-880a-49e5-89dc-137a00ee7048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>6dba7ed2-ce67-40cf-bc29-79938f77092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>c4ccce09-8229-42bd-8e93-23b52c9f6d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ซื้อหน่วยลงทุน']/parent::*</value>
      <webElementGuid>1dcabe2f-e97c-4a25-be39-ee1236050c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7110.jsp?rmf=no')]</value>
      <webElementGuid>5910d51a-1212-4672-b0db-306c9dcbb6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>8f15e59e-5df5-4753-bf33-4dc330fe7a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7110.jsp?rmf=no' and (text() = 'ซื้อหน่วยลงทุน' or . = 'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>dfb4d048-9cef-4990-b493-e928d494e50c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
