<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink</name>
   <tag></tag>
   <elementGuidId>be7d42e5-7174-4103-8987-7080ca94eeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ซื้อหน่วยลงทุน')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_7500 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f23397bd-930f-4673-8318-70149634a888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>c7c69cc9-6bf3-4bd5-97c6-0e8ba6b68f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9b07f646-fc7c-4a27-a75e-c72468db2cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>42759474-51b6-4b5d-ac0c-e5c5b7505687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_menu('7500');</value>
      <webElementGuid>0e0aebbd-3189-4d21-94fd-f3ad8e4fa332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการ</value>
      <webElementGuid>2f53d52c-f1ae-44d9-9d47-a4075453c295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_7500&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>93c68670-de67-42c8-867a-16f16b3d4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>99c67161-d22b-4753-998e-f19df2a9779f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;show_menu('7500');&quot;]</value>
      <webElementGuid>f3a4ed09-be19-40e4-8310-c278edf176c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_7500']/a</value>
      <webElementGuid>500d88ba-e9c9-40f3-aae5-a7c788bd8139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการ')]</value>
      <webElementGuid>b1b54fa4-5715-414e-9df2-7377b1d4f24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/preceding::a[6]</value>
      <webElementGuid>0f86110d-406c-4ac7-b33d-8cb404abedb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการ']/parent::*</value>
      <webElementGuid>181fd85a-c97c-47f2-ba1b-e05b9345bb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>70deda52-7633-4ab7-8f6d-b0a98673bbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>841da5c3-b91a-4cff-a440-bb04abd48903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'สรุปรายการ' or . = 'สรุปรายการ')]</value>
      <webElementGuid>26d7eb7c-9826-4243-9665-bc271d602579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[3]</value>
      <webElementGuid>675072cd-45f8-498c-a0a2-03625eafa0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7130']/a</value>
      <webElementGuid>d3ca5bab-ba68-4fd3-86e8-5f994faf3afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>101708d5-416c-46dc-b56e-321862597ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>695127a8-17ef-40fb-86e7-84a3773965db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ค้นหารายการ/ยกเลิกรายการ'])[1]/preceding::a[1]</value>
      <webElementGuid>f4824848-06a7-4301-babd-f0cbd2e76b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สับเปลี่ยนกองทุน']/parent::*</value>
      <webElementGuid>d1306b1c-3e02-4c5f-a155-156ee1ff109f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7130.jsp')]</value>
      <webElementGuid>2102b853-7f38-4cfd-b06b-37d09bd21dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a</value>
      <webElementGuid>8bf484ff-e198-4405-a02c-17f57b2a29d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7130.jsp' and (text() = 'สับเปลี่ยนกองทุน' or . = 'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>1cd1ba18-ef14-44fd-8b45-d215752a0adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[2]</value>
      <webElementGuid>aa48f929-3d4b-44c9-a944-42db582f46ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7120']/a</value>
      <webElementGuid>ddb2544d-cd6d-473e-8c07-f6a56ca8edaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>de3cffbf-018d-47bc-9293-dd3987e3bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>3b7c64cb-cff3-47dc-8cb5-3509de91b4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สับเปลี่ยนกองทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>d750d7cb-b562-4869-9d6f-17e9a6f91121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ขายคืนหน่วยลงทุน']/parent::*</value>
      <webElementGuid>71b36f56-596c-4658-bfbc-b1800303e19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7120.htm')]</value>
      <webElementGuid>e0f7d6b3-51d3-40db-a140-1b4c3c0e767b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>13c25ee9-2212-4734-9665-4be25a6c03f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7120.htm' and (text() = 'ขายคืนหน่วยลงทุน' or . = 'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>efa327ed-618a-4d05-8dfb-bc60d11a0447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_form();']</value>
      <webElementGuid>df953bf1-dddf-4814-b544-a87031514d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7110']/a</value>
      <webElementGuid>574064d8-b683-4caf-97ad-9a2bbe707939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>f4b577b3-33c7-4c0e-bfb4-e72b7b0fd976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>1770c74f-a5d6-4c16-89f4-8c6ae3bfd52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ซื้อหน่วยลงทุน']/parent::*</value>
      <webElementGuid>d979e9b6-41f7-43d8-b84b-4daf3b04807f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7110.jsp?rmf=no')]</value>
      <webElementGuid>99761d6a-c944-4b4a-accc-b0e111190c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>48682fce-0c39-43d4-8d7c-7bafbd493d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7110.jsp?rmf=no' and (text() = 'ซื้อหน่วยลงทุน' or . = 'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>1646ab7d-313e-4716-9f54-54e1da63fc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
