<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink_5</name>
   <tag></tag>
   <elementGuidId>e1cc78e7-c069-4ace-928d-5d8f5dd3a67e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'สับเปลี่ยนกองทุน')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_7500 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc5af597-1e62-4d4e-8da7-a108b36f7505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>09c5b24a-d73c-4409-ac63-bf7cbec73385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e38503a9-89b0-4e6f-b372-a77d0ef81f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>e8ee3fee-040f-4f24-ae1d-4999e9fc0888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_menu('7500');</value>
      <webElementGuid>4280f147-2c9e-484e-a531-9b03f7632913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการ</value>
      <webElementGuid>40a2c632-2c4b-4c3b-bea2-ab82f25ee018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_7500&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>69a86c09-823e-4d94-b3b1-78eddb3ad059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>bf0d9407-6897-443b-8b7e-a9215d8149b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;show_menu('7500');&quot;]</value>
      <webElementGuid>56833750-1406-414d-81cd-8a67df535b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_7500']/a</value>
      <webElementGuid>c763d1d7-a338-4b3b-afb7-27b35d315cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการ')]</value>
      <webElementGuid>09f01ec2-4b71-43ec-8deb-2cda68b0511a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/preceding::a[6]</value>
      <webElementGuid>f51ff0c5-8e60-4017-b306-6009813e2247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการ']/parent::*</value>
      <webElementGuid>283a03a4-b710-4a1f-9479-e828d8261b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>c22e648a-78a5-41b2-9f5f-eb6c5d6ffb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>26ad9142-42f7-45e6-bec6-fb1de66a256d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'สรุปรายการ' or . = 'สรุปรายการ')]</value>
      <webElementGuid>37b05293-6523-40cf-99a9-84f49d87a0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[3]</value>
      <webElementGuid>a7105b4f-1f62-4646-8891-02c4fc161cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7130']/a</value>
      <webElementGuid>48a27aa3-32bc-46b8-b5e6-9ac3c4edff84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>be20f377-37f8-43da-b556-0332da4e0334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>997c6ff7-68ff-43a8-9e12-d836a5f9e9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ค้นหารายการ/ยกเลิกรายการ'])[1]/preceding::a[1]</value>
      <webElementGuid>99f77ce9-135b-44db-996c-4b4056c6785d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สับเปลี่ยนกองทุน']/parent::*</value>
      <webElementGuid>e9c454a1-28ad-4eea-87a5-01d1aebf99a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7130.jsp')]</value>
      <webElementGuid>1bfd81fe-7e4a-4368-b106-4f177f4c6127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a</value>
      <webElementGuid>b4155e3d-87f2-497b-8ed2-e06b8f34ffb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7130.jsp' and (text() = 'สับเปลี่ยนกองทุน' or . = 'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>b79714cf-9366-4802-9fe7-013216dc7ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[2]</value>
      <webElementGuid>6a088310-acf0-4aa6-bb38-955c3c57c492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7120']/a</value>
      <webElementGuid>ea6b3378-5e5d-4025-93da-c659b16e3bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>e696191e-8711-4945-b9a7-d59ebb5acdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>4107e3a2-bb87-41fb-a0a7-45abbe25e6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สับเปลี่ยนกองทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>c3c745c4-64cf-4191-9800-f620e8c66d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ขายคืนหน่วยลงทุน']/parent::*</value>
      <webElementGuid>eae969d6-18e0-4fcc-a6f8-96f44d7ef1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7120.htm')]</value>
      <webElementGuid>8da5952a-7cef-43b2-9eb1-12d110b861ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>a85bc1d2-f778-4431-9025-8474f2455e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7120.htm' and (text() = 'ขายคืนหน่วยลงทุน' or . = 'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>550e1f0c-c51f-4c40-b15f-91434b54c6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_form();']</value>
      <webElementGuid>4dabf74f-1fc3-47be-8374-06867d781934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7110']/a</value>
      <webElementGuid>7c856ffe-ec35-4a27-8944-13a4005628ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>087f5a5f-a955-4fbb-a4ed-1cb548867903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>9af52a26-2439-4737-b602-5d265ae5876f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ซื้อหน่วยลงทุน']/parent::*</value>
      <webElementGuid>d250e175-02c2-42d8-bff4-66939070dcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7110.jsp?rmf=no')]</value>
      <webElementGuid>5c9650df-9814-4f65-97c9-d759a341dcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>ff2c4115-d4bc-4d0f-b297-c0006d25b894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7110.jsp?rmf=no' and (text() = 'ซื้อหน่วยลงทุน' or . = 'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>be95e573-a76d-43bb-b4e7-6d1081ba0ae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
