<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink_4</name>
   <tag></tag>
   <elementGuidId>e3d6fd37-014f-4526-8493-71c30bf1f46f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ขายคืนหน่วยลงทุน')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_7500 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d24f141d-32e8-45ca-8bdc-bc2e3cca4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>20a3af7b-db08-4f0a-8a52-e14444e33d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>63dd1ff1-cd78-4c5b-b034-b44745a04e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>bb156a2b-65ea-4009-b53a-ff104e399a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_menu('7500');</value>
      <webElementGuid>19992636-80ce-4359-8005-a6c90310745a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการ</value>
      <webElementGuid>b904396a-7ebf-4ef3-b788-a64e6a3e74a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_7500&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>a41c07df-cb2c-4ee7-bc13-19233fe6cc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>d5b6e3f2-fab0-471d-8869-707ec7ff89dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;show_menu('7500');&quot;]</value>
      <webElementGuid>50006fee-89bf-4928-aa62-950fe29bc4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_7500']/a</value>
      <webElementGuid>8567ab0c-ad55-4882-9bc2-6e604c2cdc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการ')]</value>
      <webElementGuid>8bdc77e1-c2c6-47bc-a947-9b7bfb3aeaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/preceding::a[6]</value>
      <webElementGuid>7bfd2f3d-9759-4887-b113-96c2cdcba7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการ']/parent::*</value>
      <webElementGuid>d763653c-0c40-4db3-8b0a-bd82491ee61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>48e73d6f-6f7f-4e12-81fb-08acf7849ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>2bd678d4-e672-4621-8649-888cf69d3ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'สรุปรายการ' or . = 'สรุปรายการ')]</value>
      <webElementGuid>e1f440cb-0de3-419e-a25d-e5a752061a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[3]</value>
      <webElementGuid>678a3002-d380-45d5-a158-0451e14d278c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7130']/a</value>
      <webElementGuid>d08f4836-1def-4c3d-b2da-35887dca5319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>29cfd881-99fe-413d-ba59-3fcff8a3e72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>8e74336d-45e1-49f4-954d-12c8cc61ceba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ค้นหารายการ/ยกเลิกรายการ'])[1]/preceding::a[1]</value>
      <webElementGuid>57f407ee-7209-4a83-b281-0a6ae8c7210a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สับเปลี่ยนกองทุน']/parent::*</value>
      <webElementGuid>6b4e14bb-8703-4125-bdc2-74c60377c1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7130.jsp')]</value>
      <webElementGuid>dc4dc926-b3b6-46d6-a97d-2fb93298e022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a</value>
      <webElementGuid>5b23ec58-b7aa-4ae0-96ea-8d739213c25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7130.jsp' and (text() = 'สับเปลี่ยนกองทุน' or . = 'สับเปลี่ยนกองทุน')]</value>
      <webElementGuid>ab8ffa0b-e6e3-47a9-a7bc-7198a29fd053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[2]</value>
      <webElementGuid>311ad2f7-ffc8-461d-b862-611b781846d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7120']/a</value>
      <webElementGuid>997c9eca-b187-490b-834b-901ebf7878c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>03bc5bfa-aec0-43fc-9a26-332d1faedd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ซื้อหน่วยลงทุน'])[1]/following::a[1]</value>
      <webElementGuid>030e8160-bb98-4c1f-98b1-4b3e8b59bc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สับเปลี่ยนกองทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>c3ce8eb6-1303-478c-ba4d-eaebe4c213cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ขายคืนหน่วยลงทุน']/parent::*</value>
      <webElementGuid>996b0557-4a56-47c5-b3e5-bce30246dc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7120.htm')]</value>
      <webElementGuid>19b165ef-9ceb-4104-bd1b-e64002b61222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>6dc3ef87-c709-427a-925c-91fc6f492759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7120.htm' and (text() = 'ขายคืนหน่วยลงทุน' or . = 'ขายคืนหน่วยลงทุน')]</value>
      <webElementGuid>b27ce681-d45d-46fe-8ffa-3a9a589abaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_form();']</value>
      <webElementGuid>edbdbbe5-b26d-4b75-8f75-7385d9bc142b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7110']/a</value>
      <webElementGuid>2766d751-3f46-40ca-b222-3aa315476bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>dc7612e6-1da9-4e9d-a371-b7b2e37c5149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ขายคืนหน่วยลงทุน'])[1]/preceding::a[1]</value>
      <webElementGuid>9e0fffe7-137a-46d5-9083-15281a62948e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ซื้อหน่วยลงทุน']/parent::*</value>
      <webElementGuid>8bcea211-94bd-4077-9f5f-7da9b94896cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7110.jsp?rmf=no')]</value>
      <webElementGuid>5ac17cbc-bbfa-478c-8b25-e0eb591f9782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>5d87472e-7a84-47b3-9433-0c84788b3179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7110.jsp?rmf=no' and (text() = 'ซื้อหน่วยลงทุน' or . = 'ซื้อหน่วยลงทุน')]</value>
      <webElementGuid>65ced087-7227-4837-9678-9746c1581c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
