<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink_1</name>
   <tag></tag>
   <elementGuidId>ce2d205e-9953-408a-bbf6-986fd8991415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '../jsp/form_7531_accept.jsp' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)' or . = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)') and @ref_element = 'Object Repository/Page_/iframe__menu_frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#span_7531 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab9ea33c-692d-4ee5-a2fa-5bb1435ffa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>63a5bd2f-4cbe-40a4-9fc0-9ccecc9e8b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../jsp/form_7531_accept.jsp</value>
      <webElementGuid>c30406b5-f7f2-4805-b4b6-63f2aafa7eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>2a0fbdd8-0257-4e6c-a12f-890fe4d5d04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_form();</value>
      <webElementGuid>18e851ec-2f8f-4dbb-b16f-aad82b644891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)</value>
      <webElementGuid>38a8601d-fda4-414e-abbc-8f5b46036987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_7531&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>594d1d3c-cf01-4762-97ea-de8593e0765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>275c4600-f67f-4edd-814f-b3a64d317337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[109]</value>
      <webElementGuid>77a64548-dcf0-4adc-a25f-9ffb764c5347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7531']/a</value>
      <webElementGuid>5ecd58d3-34f5-4db0-802f-17445d9e0535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)')]</value>
      <webElementGuid>79410be5-2e5d-4fae-91b8-9a0fe9a3cd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก'])[1]/following::a[1]</value>
      <webElementGuid>262b1672-6852-46c2-a888-41709a63388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการซื้อ-ขายที่ไม่พบบัญชีธนาคารในระบบ'])[1]/preceding::a[1]</value>
      <webElementGuid>a9dd2bb2-e530-43bc-9972-4a6318ec6a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)']/parent::*</value>
      <webElementGuid>fd52ef69-6b74-4e9b-b553-aa956b655f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../jsp/form_7531_accept.jsp')]</value>
      <webElementGuid>4241317a-8a0c-4dfe-810f-25d6aab6eabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/ul/span[4]/a</value>
      <webElementGuid>85d26fb1-83d2-4049-9cce-4ad2c2d1e989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../jsp/form_7531_accept.jsp' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)' or . = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)')]</value>
      <webElementGuid>aed6c5c1-6b35-40d1-ba60-29ad0da5ca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[108]</value>
      <webElementGuid>7f80e038-7f81-41af-a109-664e421fcf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7530']/a</value>
      <webElementGuid>4f22b5f8-d3fa-41ff-8016-e49c343f7696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก')]</value>
      <webElementGuid>61a8539f-0876-4729-a5cb-78a7e89f7fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการซื้อขายของตัวแทนขาย'])[1]/following::a[1]</value>
      <webElementGuid>c0f84a6e-30a8-4736-8e7f-ecc12e5acb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)'])[1]/preceding::a[1]</value>
      <webElementGuid>5d2013ef-877e-411d-a9a4-5d89ecd3fc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก']/parent::*</value>
      <webElementGuid>24a49630-4570-4aeb-8781-46e51cf5a902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7530.htm')]</value>
      <webElementGuid>5a10d941-a4c8-40bf-bccd-6a8c5c46b9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/ul/span[3]/a</value>
      <webElementGuid>26a6c890-f32e-480b-91da-4c76c508616c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7530.htm' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก' or . = 'สรุปรายการของกองทุน 20 อันดับแรก')]</value>
      <webElementGuid>66200b52-2ee9-47b3-819d-a96bfdc57d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
