<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hyperlink_2</name>
   <tag></tag>
   <elementGuidId>9db6d0ca-8f18-4f0f-8c4e-2f02b9398d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '../jsp/form_7531_accept.jsp' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)' or . = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)') and @ref_element = 'Object Repository/Page_/iframe__menu_frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#span_7531 > a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc52dde5-1402-4454-83f1-763b4dbc7f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>97d909fe-ac38-4629-844d-be3f878b212c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../jsp/form_7531_accept.jsp</value>
      <webElementGuid>7293fe1a-6317-4e49-ba3c-5982a1d214d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>form_frame</value>
      <webElementGuid>38bdbdae-f444-4260-b189-e577b2d5b766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_form();</value>
      <webElementGuid>d90b3ef4-9392-4688-a82b-dfda34b3de47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)</value>
      <webElementGuid>c9b971f9-96d3-4fc7-968e-07562f2e9825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_7531&quot;)/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>a2201b49-7f71-4aba-bf87-fc66a371ee32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__menu_frame</value>
      <webElementGuid>34ff3775-ca4d-4f82-a697-4499573eae18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[109]</value>
      <webElementGuid>b93d9d19-d0a3-43e8-a3af-ec2031d9cf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7531']/a</value>
      <webElementGuid>fc5f8b1b-e9f3-4474-96bf-ebbe43aec307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)')]</value>
      <webElementGuid>799e1d6e-f32c-481b-bce7-a8ab675b9d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก'])[1]/following::a[1]</value>
      <webElementGuid>950f01c9-688a-4063-a9d0-3a6a24771ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการซื้อ-ขายที่ไม่พบบัญชีธนาคารในระบบ'])[1]/preceding::a[1]</value>
      <webElementGuid>d1518f7b-0648-40e2-bea1-5b52b8a0e501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)']/parent::*</value>
      <webElementGuid>b5465d24-2d00-4075-b074-02bd7cb0c784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../jsp/form_7531_accept.jsp')]</value>
      <webElementGuid>202be312-ba6e-41fb-9427-8379281e8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/ul/span[4]/a</value>
      <webElementGuid>944d991b-1483-4bb6-bc36-cc4ce83991d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../jsp/form_7531_accept.jsp' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)' or . = 'สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)')]</value>
      <webElementGuid>0d4c3b2e-9f56-42aa-957d-8e6c09fc5858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='show_form();'])[108]</value>
      <webElementGuid>db1ee9c2-8c70-48d9-9592-ff7de5bd6b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_7530']/a</value>
      <webElementGuid>b5f3809b-0614-4ef7-b55d-787ee8496a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'สรุปรายการของกองทุน 20 อันดับแรก')]</value>
      <webElementGuid>9d68ef0a-e65c-49ae-9d8e-17d5a92a6264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการซื้อขายของตัวแทนขาย'])[1]/following::a[1]</value>
      <webElementGuid>fe101588-9fc4-493a-94a2-b7b8890f5d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก (ทุกกองทุน)'])[1]/preceding::a[1]</value>
      <webElementGuid>a1490846-d0f5-4e79-bb19-3a4894d747f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='สรุปรายการของกองทุน 20 อันดับแรก']/parent::*</value>
      <webElementGuid>4fa19a66-0b7d-42b8-83cb-37e1c064cdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'form_7530.htm')]</value>
      <webElementGuid>0e393584-1196-4358-896f-d227866ae2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/ul/span[3]/a</value>
      <webElementGuid>cfa0ff46-ec50-4388-b640-5c8301f06fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'form_7530.htm' and (text() = 'สรุปรายการของกองทุน 20 อันดับแรก' or . = 'สรุปรายการของกองทุน 20 อันดับแรก')]</value>
      <webElementGuid>abeabd60-ce02-4e49-a841-c4d834fa41f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
