<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b</name>
   <tag></tag>
   <elementGuidId>40860bda-b24e-42ca-8056-8d86d57c9874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='teller_info_tab']/tbody/tr/td[2]/a[2]/u/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > u > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ออกจากระบบ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>220e8c3d-9487-4be7-af99-6486a8b3582b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ออกจากระบบ</value>
      <webElementGuid>b5ade362-05e2-4596-84c3-6271391e2879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teller_info_tab&quot;)/tbody[1]/tr[1]/td[2]/a[2]/u[1]/b[1]</value>
      <webElementGuid>658da570-13a4-4c8e-bd8c-b21c8cd6dfff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='teller_info_tab']/tbody/tr/td[2]/a[2]/u/b</value>
      <webElementGuid>c8974b56-23f3-462b-9e8e-3ed287696bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กลับสู่หน้าจอหลัก'])[1]/following::b[1]</value>
      <webElementGuid>a5db4675-797a-4b93-911b-beb559b8aee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นโยบายเกี่ยวกับคุกกี้'])[1]/preceding::b[1]</value>
      <webElementGuid>4be7db60-8ae9-4812-9870-b7143a644235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยอมรับ'])[1]/preceding::b[1]</value>
      <webElementGuid>2721dc3b-4d9f-4734-b1aa-2f77561df829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ออกจากระบบ']/parent::*</value>
      <webElementGuid>c24974c3-da57-4e1d-8690-47447483e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/u/b</value>
      <webElementGuid>6d47e471-8726-4765-b047-f35dc4ce5810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'ออกจากระบบ' or . = 'ออกจากระบบ')]</value>
      <webElementGuid>4dff8d6c-9cb3-40ec-9a42-36892be5025e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
