<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__menu_frame</name>
   <tag></tag>
   <elementGuidId>0f3a3898-045c-44c6-9b70-93701ac9dd12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='menu_frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;menu_frame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f584c600-c843-4bdb-b97f-72fa680c3f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_frame</value>
      <webElementGuid>8d5c0b70-f705-4334-aa25-9ca51b90d992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu_frame</value>
      <webElementGuid>b7ea021f-2ec4-493b-9379-7eff3bbaa501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>885</value>
      <webElementGuid>101409c9-fbef-42cc-aaa1-2a8454987325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b037bc29-6ad1-41a8-b07d-a309c951c0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cc7122c5-cd2f-4f74-bb01-9b117e802d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73128e64-e78d-4a18-9d19-8d8b1d543584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/agent-ie-decom/sa/202510160230/form_html/menu.htm</value>
      <webElementGuid>7559432b-4e20-4692-81c3-504618b6e2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_frame&quot;)</value>
      <webElementGuid>66797e34-f0e8-4e2e-a63f-6bfeda762dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='menu_frame']</value>
      <webElementGuid>7335f794-c67f-44fb-9e46-dabd51732ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='menu_frame_span']/iframe</value>
      <webElementGuid>44200b8f-5c59-406a-a5c7-b5a59644065e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ออกจากระบบ'])[1]/following::iframe[2]</value>
      <webElementGuid>0f1391f4-9466-4fcb-a455-c719aea85382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กลับสู่หน้าจอหลัก'])[1]/following::iframe[2]</value>
      <webElementGuid>497defd4-b7da-438b-885f-681c19108e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นโยบายเกี่ยวกับคุกกี้'])[1]/preceding::iframe[2]</value>
      <webElementGuid>67cdd770-8b64-4830-9758-12be616637b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยอมรับ'])[1]/preceding::iframe[2]</value>
      <webElementGuid>dbc1701f-73a4-47f6-8ce2-608354dacd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/iframe</value>
      <webElementGuid>a52b12ff-0c2d-478b-84b6-f212469fb690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'menu_frame' and @name = 'menu_frame' and @src = '/agent-ie-decom/sa/202510160230/form_html/menu.htm']</value>
      <webElementGuid>4c00a0db-1e1e-47f5-8c26-e59bfe4624a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
