<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__switch_amount_in_baht</name>
   <tag></tag>
   <elementGuidId>e41a8c62-d7f7-4512-8c5b-f668c7c7aab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='switch_amount_in_baht']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#switch_amount_in_baht</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#switch_amount_in_baht</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2904655b-07d1-447e-b52e-e64a35374cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>switch_amount_in_baht</value>
      <webElementGuid>4bd849e2-fa93-46ce-9a95-2fb094195ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switch_amount_in_baht</value>
      <webElementGuid>51501fa2-09af-4137-938e-62ac56d032dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f322f9b2-adb5-45c6-910e-0d1952c0ef47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_number</value>
      <webElementGuid>a6ae23a1-648f-4cc7-b5f1-4a19d12ca0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7018e0dd-d561-4a55-8e20-50bc43acf8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>eb453455-acea-4884-a760-a26c81ad5746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>check_switch_in('baht');</value>
      <webElementGuid>527d7ac4-009c-4b35-9108-ef58f66ead73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>key_2_money(this);</value>
      <webElementGuid>56553ef5-8108-4917-bf8b-b03b0bafab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>fill_order_volume(this);</value>
      <webElementGuid>b35d5591-da23-459f-860d-9e2bc5383fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switch_amount_in_baht&quot;)</value>
      <webElementGuid>5d9fd57f-ff11-4f7b-af89-546485f799a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>83872a9d-81c0-4cdc-9a68-51e7315205c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='switch_amount_in_baht']</value>
      <webElementGuid>b99db7b8-53fc-4317-a959-0036481924ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7ac2298c-a135-4ad2-8b7a-8695cc51e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'switch_amount_in_baht' and @id = 'switch_amount_in_baht' and @type = 'text']</value>
      <webElementGuid>17a6cfe8-707d-426d-8721-ca284729dae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
