<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Local AuthorizeRemote Authorize_choose_auth</name>
   <tag></tag>
   <elementGuidId>cd765eb1-6e1c-4edb-b652-44fc13ec488b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='choose_auth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;choose_auth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>056c6393-7fea-4b3e-830e-f0ebee001be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3a634fd9-9c7f-4832-9cab-990cc2c45209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choose_auth</value>
      <webElementGuid>2d4f9f96-09cd-4f91-af1b-eb752d28517c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>choose_authorize_by('Local Authorize')</value>
      <webElementGuid>6cc123a8-5075-48b0-86bd-f58088ee4b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Local Authorize</value>
      <webElementGuid>7bc242ec-390b-4ec0-9ee0-c13c0ddd75d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorize_by_span&quot;)/table[1]/tbody[1]/tr[1]/td[2]/input[1]</value>
      <webElementGuid>7d05f0f5-280f-43ed-81a0-d39a69825947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__authorize_frame</value>
      <webElementGuid>642897e4-d316-4438-bce4-e031a456346c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='choose_auth']</value>
      <webElementGuid>04e40293-380b-4d1d-b83d-5c515002c2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='authorize_by_span']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>eb1b3c2c-a8f9-4117-9d80-8ccfcd1c1c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>5352d55e-b151-487b-91e7-e3b2782f5cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'choose_auth']</value>
      <webElementGuid>8b1c11bd-20e0-48db-8c5e-cf2ec1eb5851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
