<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supervisor ID_teller_login</name>
   <tag></tag>
   <elementGuidId>f31252ef-b3df-4665-9718-59349b04996d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='teller_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#teller_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#teller_login</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7271424-0933-4c9a-8c5d-eab37c7f61e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c602957d-ed1b-4e6c-9a48-8c398b75fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teller_login</value>
      <webElementGuid>2588d016-937f-4f6a-999c-95a3137740b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teller_login</value>
      <webElementGuid>1139fcc9-66c5-454a-a52b-4770381d3ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>3f516cda-2ced-4461-8c3e-e9d5ea21ca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teller_login&quot;)</value>
      <webElementGuid>e0bda833-69e3-4409-814b-eaa2fe7edb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__authorize_frame</value>
      <webElementGuid>37e6107c-70c4-4f6e-a51b-24ec49e4a08c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='teller_login']</value>
      <webElementGuid>1a291845-c84c-4ded-966e-54d42acdd28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='local_authorize_span']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>16aa93cd-4dd8-462f-acaa-92b850da0c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>fd2f1bf0-215e-4a47-be4a-f1be011eec07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'teller_login' and @id = 'teller_login']</value>
      <webElementGuid>dc1c0a20-2430-4d9c-81be-4228d1fdb1a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
