<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c_accept_fx_risk</name>
   <tag></tag>
   <elementGuidId>62e197b9-6df0-4c01-89b5-30aeb0597835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='c_accept_fx_risk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;c_accept_fx_risk&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;c_accept_fx_risk&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d87f5e5e-fa8e-4a98-84f8-2e0139e59e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f7d0cc55-11e4-459c-ae1a-bc2767448b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c_accept_fx_risk</value>
      <webElementGuid>5e8e3161-30ca-44ea-a0dd-c4f625f0ac3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>68c21c38-bda5-4920-8461-c02d139c7c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suitability_span&quot;)/table[1]/tbody[1]/tr[3]/td[1]/input[1]</value>
      <webElementGuid>bef4fe5b-d88b-424e-b4bb-4cdde5a78636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>bc3eee3c-a8cd-47c9-a3d3-5a3481fd6bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='c_accept_fx_risk']</value>
      <webElementGuid>061ec9ad-731c-49b0-80d5-d72e9e1c6f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='suitability_span']/table/tbody/tr[3]/td/input</value>
      <webElementGuid>41617d4d-3e2e-4988-83aa-1f55142e3044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>1b7a7937-08a8-426d-9faa-c38093eacf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'c_accept_fx_risk']</value>
      <webElementGuid>dc2cc29f-ac69-423a-93b2-69f85ceae7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[12]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>5d461725-48ea-4fe5-b842-1b078042400b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
