<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__c_accept_fund_risk</name>
   <tag></tag>
   <elementGuidId>599a02ff-6781-4a53-a512-5cf84d4be2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='c_accept_fund_risk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;c_accept_fund_risk&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;c_accept_fund_risk&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4f28555-70e9-428a-b86f-f89f2c5bd07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44fd6ac2-9057-467d-8556-665a6c060ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c_accept_fund_risk</value>
      <webElementGuid>6e022d99-2bd5-4a04-89e8-eab2d05fb65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>6890fb37-b76e-4b53-a6de-e5199fad56f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suitability_span&quot;)/table[1]/tbody[1]/tr[2]/td[1]/input[1]</value>
      <webElementGuid>9dcde3f9-1615-4313-95ce-d4d2e37fbd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>34300830-9997-41ae-95d6-be11ec6f5102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='c_accept_fund_risk']</value>
      <webElementGuid>618ab8a0-945f-4e3d-92f2-359c29d9e1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='suitability_span']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>2c582b9e-98a6-44a0-b53a-a3f26714e5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>031d4d04-c8f2-42a7-bb78-c72e14db16cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'c_accept_fund_risk']</value>
      <webElementGuid>dc892250-c44d-4fe5-8e16-9eaad12be808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[12]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>5a332f30-b60c-49bf-bcf1-4f2031433799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
