<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tmp_accept_conc</name>
   <tag></tag>
   <elementGuidId>5eb43c37-3031-4694-a4f7-23d8dd9d7610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tmp_accept_conc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tmp_accept_conc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;tmp_accept_conc&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb8da7ae-532b-4096-b68a-49a0c91c4d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2353ed19-c30d-4641-87de-5e96fe20c1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tmp_accept_conc</value>
      <webElementGuid>cfb05711-e286-4b8e-9c39-600982b31cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>e8d087eb-c7c1-4a95-9e94-eb087ffa3537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suitability_span&quot;)/table[1]/tbody[1]/tr[4]/td[1]/input[1]</value>
      <webElementGuid>bf07d5c7-64ee-46f9-87c9-a737f19fc964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>70d3c614-8288-426e-a42b-35cc3df6ffdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tmp_accept_conc']</value>
      <webElementGuid>26693ac6-8583-4523-bb26-740576a14ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='suitability_span']/table/tbody/tr[4]/td/input</value>
      <webElementGuid>631c66dc-1532-414c-83cf-c8726506e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>e62c12e2-cc0a-4cae-b68f-14bc27060e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tmp_accept_conc']</value>
      <webElementGuid>b86ddc8a-f696-48e2-b1ec-a00174f4703c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[12]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>d1379500-105d-4887-9231-561486fe794e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
