<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__redeem_amount_in_baht</name>
   <tag></tag>
   <elementGuidId>df28a954-f2b6-45ea-9530-d9db4a85c14b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redeem_amount_in_baht</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='redeem_amount_in_baht']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#redeem_amount_in_baht</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef90d5c4-23a0-4638-a5fb-638cc606ca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>redeem_amount_in_baht</value>
      <webElementGuid>b28e58b9-7e04-48a3-9b74-b394d9323a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redeem_amount_in_baht</value>
      <webElementGuid>a6cefc4d-3911-4a93-b150-7bb3ab0dbcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9719111-c9bf-42d9-baca-c90d777c3e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_number</value>
      <webElementGuid>c3679464-1f90-4345-95a6-14540934a96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>83278289-63db-42a8-8471-113f72b594e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>check_redeem_in('baht');</value>
      <webElementGuid>7e607b7e-e435-4578-b678-5f7926cba094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>key_2_money(this);</value>
      <webElementGuid>4cf8634b-f35f-41bd-8075-23298c55386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>fill_order_volume(this);</value>
      <webElementGuid>af21ebc4-8dfb-4164-984b-34ff72eba45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redeem_amount_in_baht&quot;)</value>
      <webElementGuid>32c7155d-f637-43c3-9af8-91a06bdb9282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>e4df540d-a888-4198-8c3d-8c6352420945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='redeem_amount_in_baht']</value>
      <webElementGuid>b669e10e-e640-4025-9d1e-94e9d314f50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='amt_span']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f35ce467-0d77-401b-b5f0-23a0a2ccf2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>2955c3c2-0ecf-4647-b410-2beb5bb7d61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'redeem_amount_in_baht' and @id = 'redeem_amount_in_baht' and @type = 'text']</value>
      <webElementGuid>2a151660-b61e-48a8-92cf-46b711b09000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
