<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Subscription Account_tmp_subscription_info</name>
   <tag></tag>
   <elementGuidId>29d41996-c3ce-4025-9f83-844f12e2550e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tmp_subscription_info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tmp_subscription_info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tmp_subscription_info</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a30ba006-fdce-465f-bdc3-4ef862f9aceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tmp_subscription_info</value>
      <webElementGuid>78b44a4d-b208-427f-984c-bea93044bba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tmp_subscription_info</value>
      <webElementGuid>9052f673-c0bd-4f62-8633-074d3d65ee01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-โปรดระบุ-BBL : 031-3-00485-5BBL : 128888888888BBL : 888-8-88888-8KBANK : 709-1-04635-5KTB : 000-6-15497-2ttb : 001-1-56489-5ttb : 777-7-77777-7SCB : 049-3-13176-1AYUDHAYA : 348-0-01084-8</value>
      <webElementGuid>49ecc287-5cb0-42ea-8058-79edceaca757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tmp_subscription_info&quot;)</value>
      <webElementGuid>7bead91c-1e84-432d-a86e-ab612e2c53fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe__form_frame</value>
      <webElementGuid>d2ceff24-f20a-44f4-be4a-d482ad1dade3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tmp_subscription_info']</value>
      <webElementGuid>122c3c4f-47ed-470f-82d6-64a45ddd1909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='subscription_span']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>5f636077-3c70-4858-b1f7-07bdda9dc4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription Account'])[1]/following::select[1]</value>
      <webElementGuid>45c5f6f6-70ae-4dbd-b1b6-bce9f24012a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสผู้ขาย'])[1]/preceding::select[1]</value>
      <webElementGuid>587abd0e-a2c8-49c4-a682-0b0f5ec12299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสผู้แนะนำ'])[1]/preceding::select[1]</value>
      <webElementGuid>5c7867d8-0ae8-4a96-82e0-c128325ab2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[8]/table/tbody/tr/td[2]/select</value>
      <webElementGuid>00569a7b-b01b-454f-98c7-ff5d38bad6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tmp_subscription_info' and @id = 'tmp_subscription_info' and (text() = '-โปรดระบุ-BBL : 031-3-00485-5BBL : 128888888888BBL : 888-8-88888-8KBANK : 709-1-04635-5KTB : 000-6-15497-2ttb : 001-1-56489-5ttb : 777-7-77777-7SCB : 049-3-13176-1AYUDHAYA : 348-0-01084-8' or . = '-โปรดระบุ-BBL : 031-3-00485-5BBL : 128888888888BBL : 888-8-88888-8KBANK : 709-1-04635-5KTB : 000-6-15497-2ttb : 001-1-56489-5ttb : 777-7-77777-7SCB : 049-3-13176-1AYUDHAYA : 348-0-01084-8')]</value>
      <webElementGuid>089e3f11-841a-48b3-8031-77662805164c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
