<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>c6d9088b-49a4-4072-9584-d3ce8f2e9153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='เลขที่ผู้ถือหน่วย'])[1]/following::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;000-0-00001-2&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1ea1ca16-2d1d-4ba6-a045-08d7ed1423ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000-0-00001-2</value>
      <webElementGuid>e0935223-0d4b-46c4-9067-af07f4ddb897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[2]</value>
      <webElementGuid>193c96cd-a3f9-4bb1-a7e2-4381a8fbd66b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เลขที่ผู้ถือหน่วย'])[1]/following::td[1]</value>
      <webElementGuid>6c082682-6b8c-4343-a293-ba7c40271484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน'])[1]/following::td[2]</value>
      <webElementGuid>7ab61582-b16c-4cfd-9606-2ab4e099ee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='วันที่ - เวลา ที่ทำรายการ'])[1]/preceding::td[1]</value>
      <webElementGuid>2de4f72a-d5c2-435e-824e-f11b4dae8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อผู้ถือหน่วยลงทุน'])[1]/preceding::td[3]</value>
      <webElementGuid>c3e90c80-4553-4f87-b14c-5d4a3bf4cb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='000-0-00001-2']/parent::*</value>
      <webElementGuid>9c76a0d2-8a17-4472-ad2b-d331d12066da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>bc223bf9-2886-4de6-b1a0-30c62a681cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '000-0-00001-2' or . = '000-0-00001-2')]</value>
      <webElementGuid>773856e3-1a4b-4d9f-aa46-9da4a4eb3b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ใบยืนยันคำสั่งขายหน่วยลงทุน'])[1]/following::td[2]</value>
      <webElementGuid>9f528bc8-b981-4b39-b5e1-b6075fe7b242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จำนวน'])[1]/following::td[1]</value>
      <webElementGuid>23a8bc37-ec43-43ea-9b7d-dc4d8ca4f897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES-Global Income (I20)'])[1]/following::td[4]</value>
      <webElementGuid>af21511f-8015-4afc-ab58-6214e7f188ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สำหรับเจ้าหน้าที่'])[1]/preceding::td[3]</value>
      <webElementGuid>e96c3ac9-e466-437e-a93e-2fbfaf496563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher:'])[1]/preceding::td[4]</value>
      <webElementGuid>5a1b331e-9b02-45ae-8871-ca5a76ae3c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100,000.00 บาท']/parent::*</value>
      <webElementGuid>a9b54d8d-f5f9-4f62-9706-c9becc63dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]</value>
      <webElementGuid>e909a46d-0e7b-4688-8093-b865f4f9f54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '100,000.00 บาท' or . = '100,000.00 บาท')]</value>
      <webElementGuid>2b200a38-4f49-4b72-b9fb-32a63b5b64c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
