<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u</name>
   <tag></tag>
   <elementGuidId>750013a4-6980-4c51-9eb7-c287a5a04956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='เลขที่ผู้ถือหน่วย'])[1]/preceding::u[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>bab21a33-1a45-4ee5-a050-15b3fddb35af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน</value>
      <webElementGuid>bf6e7a35-57f1-4594-9329-5a94a202554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/b[1]/font[1]/u[1]</value>
      <webElementGuid>a2dcc580-2465-49f5-9e82-4148e9f36b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เลขที่ผู้ถือหน่วย'])[1]/preceding::u[1]</value>
      <webElementGuid>05bc7690-87cc-4acb-9a01-0a28eb8c014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='วันที่ - เวลา ที่ทำรายการ'])[1]/preceding::u[1]</value>
      <webElementGuid>b6a82125-65d4-49c6-9baf-f859da35a14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน']/parent::*</value>
      <webElementGuid>d36c7185-bb32-4bf6-a621-e3dc601b1c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>f522c79a-0c7c-4ca1-a8e1-a74e05b012bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน' or . = 'ใบยืนยันคำสั่งสับเปลี่ยนหน่วยลงทุน')]</value>
      <webElementGuid>7876cffe-f767-41bc-a652-67d9d2db6d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ใบยืนยันคำสั่งขายหน่วยลงทุน']/parent::*</value>
      <webElementGuid>6145d86d-d47d-400f-af9c-e819fdb4adee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'ใบยืนยันคำสั่งขายหน่วยลงทุน' or . = 'ใบยืนยันคำสั่งขายหน่วยลงทุน')]</value>
      <webElementGuid>98a7a1c8-d639-45e6-aea5-23375519900f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ใบยืนยันคำสั่งซื้อหน่วยลงทุน']/parent::*</value>
      <webElementGuid>674c729c-d9de-4f26-a8a8-286e44e01248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'ใบยืนยันคำสั่งซื้อหน่วยลงทุน' or . = 'ใบยืนยันคำสั่งซื้อหน่วยลงทุน')]</value>
      <webElementGuid>d5f8e7b9-dedb-4e7b-8341-f39a3323a353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
